server:
  port: 8082

#  servlet:
#    context-path: /demo

spring:
  application:
    name: euraka-clientdemo
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cilicili?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/jxlg6216/config
#          search-paths: clientdemo
#      name: cilicili-clientdemo-config
#      profile: pro
#      discovery:
#        service-id: cilicili-clientdemo-config
#        enabled: true
#      fail-fast: true
#      label: master

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: clientdemo
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.rk6216.eureka_clientdemo.dao
