#端口配置
server:
  port: 8088
  servlet:
    context-path: /video
#spring cloud admin配置?看清楚client和server端的配置
#management:
#  endpoint:
#    health:
#      show-details: always
#  endpoints:
#    web:
#      exposure:
#        include: ["health","info"]
spring:
  application:
    name: client-videoplay
  boot:
    admin:
      client:
#        指定admin的server地址
        url: http://localhost:9433
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/cilicili?characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis配置
  redis:
    database: 0
    port: 6379
    host: localhost
    password: root
    timeout: 5000ms
    jedis:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
#eurake配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
  instance:
    prefer-ip-address: true
    instance-id: videoplay
#Mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: cn.rk6216.client_videoplay8088.dao
#pagehelper分页插件配置
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
#开启监控所权限,admin功能
management:
  endpoints:
    web:
      exposure:
        include: "*"