package cn.rk6216.entityandtools.mapper;


import cn.rk6216.entityandtools.entitys.VideoComment;
import cn.rk6216.entityandtools.entitys.VideoCommentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoCommentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int countByExample(VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int deleteByExample(VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int deleteByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int insert(VideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int insertSelective(VideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    List<VideoComment> selectByExample(VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    VideoComment selectByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") VideoComment record, @Param("example") VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByExample(@Param("record") VideoComment record, @Param("example") VideoCommentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByPrimaryKeySelective(VideoComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByPrimaryKey(VideoComment record);
}