package cn.rk6216.entityandtools.mapper;


import cn.rk6216.entityandtools.entitys.VideoInformation;
import cn.rk6216.entityandtools.entitys.VideoInformationExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VideoInformationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int countByExample(VideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int deleteByExample(VideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int deleteByPrimaryKey(String videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int insert(VideoInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int insertSelective(VideoInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    List<VideoInformation> selectByExample(VideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    VideoInformation selectByPrimaryKey(String videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByExampleSelective(@Param("record") VideoInformation record, @Param("example") VideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByExample(@Param("record") VideoInformation record, @Param("example") VideoInformationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByPrimaryKeySelective(VideoInformation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table video_information
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    int updateByPrimaryKey(VideoInformation record);
}