package cn.rk6216.entityandtools.entitys;

import java.util.ArrayList;
import java.util.List;

public class CommentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public CommentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPlusIdIsNull() {
            addCriterion("plus_id is null");
            return (Criteria) this;
        }

        public Criteria andPlusIdIsNotNull() {
            addCriterion("plus_id is not null");
            return (Criteria) this;
        }

        public Criteria andPlusIdEqualTo(String value) {
            addCriterion("plus_id =", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdNotEqualTo(String value) {
            addCriterion("plus_id <>", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdGreaterThan(String value) {
            addCriterion("plus_id >", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdGreaterThanOrEqualTo(String value) {
            addCriterion("plus_id >=", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdLessThan(String value) {
            addCriterion("plus_id <", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdLessThanOrEqualTo(String value) {
            addCriterion("plus_id <=", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdLike(String value) {
            addCriterion("plus_id like", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdNotLike(String value) {
            addCriterion("plus_id not like", value, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdIn(List<String> values) {
            addCriterion("plus_id in", values, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdNotIn(List<String> values) {
            addCriterion("plus_id not in", values, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdBetween(String value1, String value2) {
            addCriterion("plus_id between", value1, value2, "plusId");
            return (Criteria) this;
        }

        public Criteria andPlusIdNotBetween(String value1, String value2) {
            addCriterion("plus_id not between", value1, value2, "plusId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNull() {
            addCriterion("comment_id is null");
            return (Criteria) this;
        }

        public Criteria andCommentIdIsNotNull() {
            addCriterion("comment_id is not null");
            return (Criteria) this;
        }

        public Criteria andCommentIdEqualTo(String value) {
            addCriterion("comment_id =", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotEqualTo(String value) {
            addCriterion("comment_id <>", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThan(String value) {
            addCriterion("comment_id >", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdGreaterThanOrEqualTo(String value) {
            addCriterion("comment_id >=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThan(String value) {
            addCriterion("comment_id <", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLessThanOrEqualTo(String value) {
            addCriterion("comment_id <=", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdLike(String value) {
            addCriterion("comment_id like", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotLike(String value) {
            addCriterion("comment_id not like", value, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdIn(List<String> values) {
            addCriterion("comment_id in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotIn(List<String> values) {
            addCriterion("comment_id not in", values, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdBetween(String value1, String value2) {
            addCriterion("comment_id between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andCommentIdNotBetween(String value1, String value2) {
            addCriterion("comment_id not between", value1, value2, "commentId");
            return (Criteria) this;
        }

        public Criteria andPlusValueIsNull() {
            addCriterion("plus_value is null");
            return (Criteria) this;
        }

        public Criteria andPlusValueIsNotNull() {
            addCriterion("plus_value is not null");
            return (Criteria) this;
        }

        public Criteria andPlusValueEqualTo(String value) {
            addCriterion("plus_value =", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueNotEqualTo(String value) {
            addCriterion("plus_value <>", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueGreaterThan(String value) {
            addCriterion("plus_value >", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueGreaterThanOrEqualTo(String value) {
            addCriterion("plus_value >=", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueLessThan(String value) {
            addCriterion("plus_value <", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueLessThanOrEqualTo(String value) {
            addCriterion("plus_value <=", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueLike(String value) {
            addCriterion("plus_value like", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueNotLike(String value) {
            addCriterion("plus_value not like", value, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueIn(List<String> values) {
            addCriterion("plus_value in", values, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueNotIn(List<String> values) {
            addCriterion("plus_value not in", values, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueBetween(String value1, String value2) {
            addCriterion("plus_value between", value1, value2, "plusValue");
            return (Criteria) this;
        }

        public Criteria andPlusValueNotBetween(String value1, String value2) {
            addCriterion("plus_value not between", value1, value2, "plusValue");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameIsNull() {
            addCriterion("comment_username is null");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameIsNotNull() {
            addCriterion("comment_username is not null");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameEqualTo(String value) {
            addCriterion("comment_username =", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameNotEqualTo(String value) {
            addCriterion("comment_username <>", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameGreaterThan(String value) {
            addCriterion("comment_username >", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("comment_username >=", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameLessThan(String value) {
            addCriterion("comment_username <", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameLessThanOrEqualTo(String value) {
            addCriterion("comment_username <=", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameLike(String value) {
            addCriterion("comment_username like", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameNotLike(String value) {
            addCriterion("comment_username not like", value, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameIn(List<String> values) {
            addCriterion("comment_username in", values, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameNotIn(List<String> values) {
            addCriterion("comment_username not in", values, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameBetween(String value1, String value2) {
            addCriterion("comment_username between", value1, value2, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentUsernameNotBetween(String value1, String value2) {
            addCriterion("comment_username not between", value1, value2, "commentUsername");
            return (Criteria) this;
        }

        public Criteria andCommentStatusIsNull() {
            addCriterion("comment_status is null");
            return (Criteria) this;
        }

        public Criteria andCommentStatusIsNotNull() {
            addCriterion("comment_status is not null");
            return (Criteria) this;
        }

        public Criteria andCommentStatusEqualTo(String value) {
            addCriterion("comment_status =", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotEqualTo(String value) {
            addCriterion("comment_status <>", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusGreaterThan(String value) {
            addCriterion("comment_status >", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusGreaterThanOrEqualTo(String value) {
            addCriterion("comment_status >=", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusLessThan(String value) {
            addCriterion("comment_status <", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusLessThanOrEqualTo(String value) {
            addCriterion("comment_status <=", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusLike(String value) {
            addCriterion("comment_status like", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotLike(String value) {
            addCriterion("comment_status not like", value, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusIn(List<String> values) {
            addCriterion("comment_status in", values, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotIn(List<String> values) {
            addCriterion("comment_status not in", values, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusBetween(String value1, String value2) {
            addCriterion("comment_status between", value1, value2, "commentStatus");
            return (Criteria) this;
        }

        public Criteria andCommentStatusNotBetween(String value1, String value2) {
            addCriterion("comment_status not between", value1, value2, "commentStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated do_not_delete_during_merge Sun Dec 22 17:05:56 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table comment
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}