package cn.rk6216.entityandtools.entitys;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.plus_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String plusId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.plus_value
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String plusValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_username
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column comment.comment_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.plus_id
     *
     * @return the value of comment.plus_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getPlusId() {
        return plusId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.plus_id
     *
     * @param plusId the value for comment.plus_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setPlusId(String plusId) {
        this.plusId = plusId == null ? null : plusId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_id
     *
     * @return the value of comment.comment_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_id
     *
     * @param commentId the value for comment.comment_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.plus_value
     *
     * @return the value of comment.plus_value
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getPlusValue() {
        return plusValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.plus_value
     *
     * @param plusValue the value for comment.plus_value
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setPlusValue(String plusValue) {
        this.plusValue = plusValue == null ? null : plusValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_username
     *
     * @return the value of comment.comment_username
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentUsername() {
        return commentUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_username
     *
     * @param commentUsername the value for comment.comment_username
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentUsername(String commentUsername) {
        this.commentUsername = commentUsername == null ? null : commentUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column comment.comment_status
     *
     * @return the value of comment.comment_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column comment.comment_status
     *
     * @param commentStatus the value for comment.comment_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus == null ? null : commentStatus.trim();
    }
}