package cn.rk6216.entityandtools.entitys;

public class VideoComment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.comment_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.video_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.comment_value
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.comment_username
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.comment_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.comment_praise
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private Integer commentPraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.comment_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String commentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_comment.location_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String locationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.comment_id
     *
     * @return the value of video_comment.comment_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentId() {
        return commentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.comment_id
     *
     * @param commentId the value for video_comment.comment_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentId(String commentId) {
        this.commentId = commentId == null ? null : commentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.video_id
     *
     * @return the value of video_comment.video_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.video_id
     *
     * @param videoId the value for video_comment.video_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.comment_value
     *
     * @return the value of video_comment.comment_value
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentValue() {
        return commentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.comment_value
     *
     * @param commentValue the value for video_comment.comment_value
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentValue(String commentValue) {
        this.commentValue = commentValue == null ? null : commentValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.comment_username
     *
     * @return the value of video_comment.comment_username
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentUsername() {
        return commentUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.comment_username
     *
     * @param commentUsername the value for video_comment.comment_username
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentUsername(String commentUsername) {
        this.commentUsername = commentUsername == null ? null : commentUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.comment_status
     *
     * @return the value of video_comment.comment_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentStatus() {
        return commentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.comment_status
     *
     * @param commentStatus the value for video_comment.comment_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentStatus(String commentStatus) {
        this.commentStatus = commentStatus == null ? null : commentStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.comment_praise
     *
     * @return the value of video_comment.comment_praise
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public Integer getCommentPraise() {
        return commentPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.comment_praise
     *
     * @param commentPraise the value for video_comment.comment_praise
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentPraise(Integer commentPraise) {
        this.commentPraise = commentPraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.comment_time
     *
     * @return the value of video_comment.comment_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getCommentTime() {
        return commentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.comment_time
     *
     * @param commentTime the value for video_comment.comment_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setCommentTime(String commentTime) {
        this.commentTime = commentTime == null ? null : commentTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_comment.location_time
     *
     * @return the value of video_comment.location_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getLocationTime() {
        return locationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_comment.location_time
     *
     * @param locationTime the value for video_comment.location_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setLocationTime(String locationTime) {
        this.locationTime = locationTime == null ? null : locationTime.trim();
    }
}