package cn.rk6216.entityandtools.entitys;

public class VideoInformation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_title
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_introduction
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoIntroduction;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_author
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.vidoe_praise
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private Integer vidoePraise;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_collections
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private Integer videoCollections;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column video_information.video_type
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    private String videoType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_id
     *
     * @return the value of video_information.video_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_id
     *
     * @param videoId the value for video_information.video_id
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoId(String videoId) {
        this.videoId = videoId == null ? null : videoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_title
     *
     * @return the value of video_information.video_title
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoTitle() {
        return videoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_title
     *
     * @param videoTitle the value for video_information.video_title
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle == null ? null : videoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_introduction
     *
     * @return the value of video_information.video_introduction
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoIntroduction() {
        return videoIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_introduction
     *
     * @param videoIntroduction the value for video_information.video_introduction
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoIntroduction(String videoIntroduction) {
        this.videoIntroduction = videoIntroduction == null ? null : videoIntroduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_author
     *
     * @return the value of video_information.video_author
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoAuthor() {
        return videoAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_author
     *
     * @param videoAuthor the value for video_information.video_author
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoAuthor(String videoAuthor) {
        this.videoAuthor = videoAuthor == null ? null : videoAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_status
     *
     * @return the value of video_information.video_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoStatus() {
        return videoStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_status
     *
     * @param videoStatus the value for video_information.video_status
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoStatus(String videoStatus) {
        this.videoStatus = videoStatus == null ? null : videoStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_time
     *
     * @return the value of video_information.video_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoTime() {
        return videoTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_time
     *
     * @param videoTime the value for video_information.video_time
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoTime(String videoTime) {
        this.videoTime = videoTime == null ? null : videoTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.vidoe_praise
     *
     * @return the value of video_information.vidoe_praise
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public Integer getVidoePraise() {
        return vidoePraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.vidoe_praise
     *
     * @param vidoePraise the value for video_information.vidoe_praise
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVidoePraise(Integer vidoePraise) {
        this.vidoePraise = vidoePraise;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_collections
     *
     * @return the value of video_information.video_collections
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public Integer getVideoCollections() {
        return videoCollections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_collections
     *
     * @param videoCollections the value for video_information.video_collections
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoCollections(Integer videoCollections) {
        this.videoCollections = videoCollections;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column video_information.video_type
     *
     * @return the value of video_information.video_type
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public String getVideoType() {
        return videoType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column video_information.video_type
     *
     * @param videoType the value for video_information.video_type
     *
     * @mbggenerated Sun Dec 22 17:05:56 CST 2019
     */
    public void setVideoType(String videoType) {
        this.videoType = videoType == null ? null : videoType.trim();
    }
}