server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: false
    command:
      default:
        excution:
          timeout:
            enabled: false
          isolation:
            thread:
              timeoutInMilliseconds: 60000

# 设置ribbon超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
